#7 Board UI MockUp_Data
hatchways/team-granite pull request #37
Opened 2021-10-27 13:43 UTC by Vicheans

### What this PR does (required):
- #7  Mock-up data for the Draggable FrontEnd [directory](https://github.com/hatchways/team-granite/blob/23_DragNDrop_to_Board/client/src/components/DragAndDrop/data.jsx)

### Screenshots / Videos (front-end only):
![mockData](https://user-images.githubusercontent.com/49110294/139655298-689149f9-7154-47ff-8432-0a6b85417543.png)
![mockData0](https://user-images.githubusercontent.com/49110294/139655301-a106df9a-6f48-4a2f-a14a-d88845997c5f.png)
![mockData1](https://user-images.githubusercontent.com/49110294/139655305-2d31b8fd-f16f-4f6f-9ad0-8a6e3b5244d9.png)
![mockData2](https://user-images.githubusercontent.com/49110294/139655314-0bed1232-a4b2-4e5d-8671-7f4a634967fc.png)

### Any information needed to test this feature (required):
- @tejasj1718  @gami34 @moffatethan  Kindly take a look at the attached screenshots to see the suggested SCHEMA design for the Database. Kindly revert in case of changes on time for seamless integration. Many thanks!

2021-10-30 22:03 UTC, Vicheans commented on client/src/components/DragAndDrop/dragNdrop.jsx
> +        }
Alright, Ethan. looking forward to the developments

2021-10-30 22:04 UTC, Vicheans commented on client/src/components/DragAndDrop/dragNdrop.jsx
> +    </div>)
Alright, many thanks for the feedback.

2021-10-30 22:29 UTC, Vicheans commented
> Left some comments on changing the mock data, as well as removing a unnecessary component. Thanks!

I got the component removal part, could you please point the correction for the mock data. Best regards

2021-11-02 16:47 UTC, moffatethan requested changes
Just some comments but overall this is coming together.

2021-11-02 16:47 UTC, moffatethan commented on client/src/components/DragAndDrop/assets/item.module.scss
> +
I actually would like to see you use the `makeStyles` from MUI as oppposed to Sass stylesheets.

2021-11-02 16:47 UTC, moffatethan commented on client/src/components/DragAndDrop/drag&drop.jsx
> +            const $_columns = {
Could you explain the naming choice here? I don't see the point of `$_columns`

2021-11-02 16:47 UTC, moffatethan commented on client/src/components/DragAndDrop/drag&drop.jsx
> +    const [ordered, setOrdered] = useState(Object.keys(data))
Curious if we have to have a state for tracking the order? Couldn't we just work off the columns list and do the sorting there with array methods?

2021-11-03 12:53 UTC, merged