FEAT: detailed card completed with correction based on previous issue #1
hatchways/team-granite pull request #47
Opened 2021-11-02 16:18 UTC by gami34

What this PR does (required):
all corrections raised during issue #1 were corrected and implemented
API to add Card's description, deadline, and comment feature has been addressed

Screenshots / Videos (front-end only):
Post at least one screenshot to show the feature in action. Only required in front-end work

Any information needed to test this feature (required):
add a MongoDB URI to the "MONGO_URI" key in an .env file on the servers' folder root directory. A MongoDB Atlas URI will be perfect for this
then add a Secret String Type Data to the "SECRET" key on the .env on the servers' folder root directory.
then run script below on your terminal from the server's folder root directory

```bash
$ npm run dev
```
Kindly find API Documentation for data format purposes
https://documenter.getpostman.com/view/10413337/UV5f6tSz

Any issues with the current functionality (optional):
List any problems where you were not able to complete all tasks on ticket
List any problems this PR may cause for the project or other active PRs
Post a screenshot/video of the problem, along with detailed console outputs where applicable

2021-11-02 19:28 UTC, ezeilo-su requested changes
Quite a good work on this one :+1:
#### I have some comments for you
- So many file changes occurred due to your linters setup which is not consistent with the provided style guide. Please address this and make sure to apply proper formatting on your code, as I could not comment on each line of code in all cases.
- Your code is well written and nicely documented. Please remove unnecessary comments and console logs.
Please make the requested changes and wait for approval by a team member.
Happy coding!

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/board.js
> +    // refetch the board data n populate
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/board.js
> +  //  pop the columnId if it exist
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/board.js
> +  // update the user board
This one too

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/card.js
> +  // create the column
Let get rid of this comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/card.js
> +  // update the Column Card List board
Get rid of this one

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/card.js
> +    // update the user board
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  // create the column
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  // update the user board
Remove

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +    // update the user board
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  //  pop the cardId if it exist
Also remove this one

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  // update the Column with new cardId
This one too

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  //  pop the cardId if it exist
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  // update the Column with new cardId
Remove comment

2021-11-02 19:28 UTC, ezeilo-su commented on server/models/column.js
> +  // update the card with its new targetId
Remove comment

2021-11-03 22:54 UTC, tejasj1718 commented
Hey Gideon,

I think you must merge this PR without waiting for any approval and merge the original issue. If you added another new issue into this PR then do not do that. You must open a new PR into main for that. Please clarify this with Ethan as well!

2021-11-04 06:58 UTC, gami34 commented
Dear Team,

All comments and console logs have been taken out.

we are still maintaining the same Linting

2021-11-04 07:04 UTC, gami34 commented on server/models/board.js
> +    this.model('Column').deleteMany({ _Id: columnObjectId })
thanks allot for this

2021-11-05 22:58 UTC, moffatethan approved these changes
@gami34 Good changes! 🚀

2021-11-06 06:42 UTC, merged