Front End Plugin Card File Attachment
hatchways/team-granite pull request #75
Opened 2021-11-17 04:41 UTC by tejasj1718

### What this PR does (required):
- Implements the FE Plugin Card File Attachment
- Uses storybook to view the changes in isolation.
- Adds mock file data and another File Upload component.

### Screenshots / Videos (front-end only):
- The File Attachment Plugin. Will be placed on the detailed card.
![PRfeFileAttach](https://user-images.githubusercontent.com/55607809/142135603-8fd6058a-b087-4c7d-a3f8-f9ebc06f37d6.png)

### Any information needed to test this feature (required):
- run the command `npm run storybook`
- Test the component.

### Any issues with the current functionality (optional):
- Not hooked up to the backend, uses mock data.
- Overlap between image upload and file upload component, could use a refactor.

2021-11-17 15:06 UTC, ezeilo-su requested changes
Nice work, @tejasj1718. A few minor comments, though. :smiley:

2021-11-17 15:06 UTC, ezeilo-su commented on client/src/components/plugins/FileAttach/FileDisplay.tsx
> +      <a href={file.url} download>
Please use MUI `Link` component for `a` element

2021-11-17 15:06 UTC, ezeilo-su commented on client/src/components/plugins/FileAttach/FileAttach.tsx
> +    //This function will upload files and set the files state.
Please be sure to remove this comment :smile:

2021-11-19 04:50 UTC, moffatethan approved these changes
Good work!

2021-11-19 15:07 UTC, merged